version: 2
jobs:
  build:
    docker:
      - image: circleci/node:carbon
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run Linter
          command: yarn lint

      - run:
          name: Run Client Test Suite
          command: cd ./client && yarn client:test

      - run:
          name: Run Server Test Suite
          command: cd ./server && yarn server:test
